### PR TITLE
Allow multiple axis for summary plots

### LINKED ISSUE #140: Plot different keywords using second axis
Users would like to plot different keywords together in the same plot, using a second axis.

First step Investigate if webviz support this

### PR DESCRIPTION
**Pull request by DanSava**
Closes #140

### CODE REVIEW

**Comment by DanSava** [comment]
The solution in this PR allows for multiple summary keys to be plotted against each other with different y-axis but I could not find any way of displaying the y-axis ranges and titles without them overlapping when the user tries to compare more than 2 summary keys.

**Comment by verveerpj** [comment]
> The solution in this PR allows for multiple summary keys to be plotted against each other with different y-axis but I could not find any way of displaying the y-axis ranges and titles without them overlapping when the user tries to compare more than 2 summary keys.

It seems you have to manually position them as in this example: https://plotly.com/python/multiple-axes/ That could get complicated with many axes.

Maybe having more than two axes is too ambitious. How about another approach where we allow only one additional axis on the right side and let the user in a second dropdown select any keys he/she wants to plot?

**Comment by DanSava** [comment]
> It seems you have to manually position them as in this example: https://plotly.com/python/multiple-axes/ That could get complicated with many axes.

I tried that first using the example you have pointed at but it requires the width and position of the graph to be changed in order to accommodate for the extra axis if we do not want them to overlap and even doing that adding 4 axis requires the plot width to be shrunk quite a bit.

> Maybe having more than two axes is too ambitious. How about another approach where we allow only one additional axis on the right side and let the user in a second dropdown select any keys he/she wants to plot?

This is a good idea, would that also require to fix the number of keys allowed in the first dropdown also to 1? 
If we do not fix the number of keys in the first dropdown to 1 will there be any value in the second axis added?

**Comment by verveerpj** [comment]
In principle we should be able to add as many lines to each axis as you want, and that is probably something to keep. But then it becomes difficult to see to which axis a plot belongs. Then you need to visually distinguish them, maybe by using dashed lines and different symbols for the second axis?

**Review by verveerpj — COMMENTED** [review]
Is it correct that we decided to leave this change as you proposed before?

**Comment by DanSava** [comment]
yes, that was what was decided.

**Review by verveerpj — APPROVED** [review]

**Pull request merged**
