### PR TITLE
Limit summary value selection to two keys

### LINKED ISSUE #161: Summary values as function of date
The plot can have multiple y-axis, sometimes overlapping, which can make the plot hard to read. We can look into removing multiple y-axis, or try to implement some logic on top of the current implementation.

### PR DESCRIPTION
**Pull request by frode-aarstad**
Fixes #161

### CODE REVIEW

**Review by DanSava — COMMENTED** [review]
Is it possible to only have one key in the plot? And not the same key twice?

**Comment by frode-aarstad** [comment]
> Is it possible to only have one key in the plot? And not the same key twice?

One key is possible. Same key twice is currently not

**Comment by DanSava** [comment]
What I mean by "same key twice":
Screenshot from 2022-03-21 18-37-43

The key `Day` is used for both key1 and key2 and this is the default (first time the plot page is opened) 

It would be nice if this would be the default when opening the page:
Screenshot from 2022-03-21 18-41-20

**Comment by frode-aarstad** [comment]
I have implemented @DanSavas suggestions ⬆️ . Initially only the first value is selected.

**Review by DanSava — APPROVED** [review]
LGTM :+1:

**Pull request merged**
